### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by DIOHz0r** [genemu/GenemuFormBundle#348]
There are a lot of push request (fixes and improvements) on this bundle and Genemu hasn't have show any activity in more than a month. Is someone working on this? :(

BTW the TinyMCE isn't working with the last version 4

**Comment by Soullivaneuh** [comment]
This issue seems to be actual. No commit since december 2014.

@bamarni @genemu is this project still maintained? Do you need help?

I can join contributors team to give me my help and move up this project if you want.

Regards.

**Comment by webdevilopers** [comment]
:+1: @Soullivaneuh ! It would be nice to see some Sonata Admin contributors helping with this bundle.
I love the Sonata Core form field types like Autocompleter with Select2 which feels like a standard by now.

Would be nice to have it in other bundles too btw:
* https://github.com/lexik/LexikFormFilterBundle/issues/64

**Comment by Soullivaneuh** [comment]
ping

**Comment by bamarni** [comment]
Sorry guys for the delay, indeed the project isn't maintained since a while.

To make the project up and running again I think the priority is to fix the test suite first, I'll take a look at it as soon as possible, if someone feels like submitting a PR for it feel free too.

@Soullivaneuh I'd really like to have you as a maintainer if you're still interested, unfortunately I cannot add you, as I'm not the owner. Could you try to ping @genemu and ask him?

**Comment by Soullivaneuh** [comment]
> @Soullivaneuh I'd really like to have you as a maintainer if you're still interested, unfortunately I cannot add you, as I'm not the owner. Could you try to ping @genemu and ask him?

Seems you already did right now. :-)
